# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Atul's Blog
email: atulanand94@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My experiments with technology
baseurl: "/blog-atul" # the subpath of your site, e.g. /blog
url: "http://atulr.com" # the base hostname & protocol for your site
twitter_username: atulanand94
github_username:  master-atul
website: http://atulr.com
author: atul

paginate: 10
paginate_path: "/page:num"

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag
  - jekyll-paginate

theme: jekyll-theme-cayman